/**
 * Static pool of 45 curated example win prompts.
 * D-09: Hardcoded in V1; personalization is V2+.
 * Format: short, first-person, past-tense, plain phrases.
 * Used by selectDailyPrompts() to show 3 daily rotating inspirations.
 */
export const EXAMPLE_PROMPTS: string[] = [
  "I helped a colleague today",
  "I finished something I'd been avoiding",
  "I showed up even when I didn't feel like it",
  "I learned something new today",
  "I made someone smile today",
  "I kept a promise to myself",
  "I took a break when I needed one",
  "I spoke up for myself today",
  "I completed a task I kept putting off",
  "I asked for help when I needed it",
  "I was kind to someone today",
  "I got some exercise in",
  "I cooked a healthy meal",
  "I reached out to an old friend",
  "I started something I've been putting off",
  "I said no to something that didn't serve me",
  "I spent quality time with someone I care about",
  "I read something that challenged my thinking",
  "I solved a problem at work",
  "I made progress on a personal project",
  "I got a full night's sleep",
  "I drank enough water today",
  "I took a walk outside",
  "I expressed gratitude to someone",
  "I cleaned or organized something",
  "I met a deadline",
  "I tried something outside my comfort zone",
  "I set a boundary that needed to be set",
  "I made a decision I'd been putting off",
  "I listened more than I spoke today",
  "I handled a stressful moment calmly",
  "I admitted I was wrong about something",
  "I celebrated someone else's win",
  "I focused for a solid stretch of time",
  "I saved money instead of spending it",
  "I took care of my mental health today",
  "I followed through on something I committed to",
  "I fixed something that was broken",
  "I wrote down my thoughts",
  "I practiced a skill I'm working on",
  "I gave someone honest feedback",
  "I asked a good question",
  "I made someone's day a little easier",
  "I stayed present in a conversation",
  "I forgave myself for something",
];
